Sausage.create!([
  {name: "Hot Italian", description: "Pork sausage with chile peppers", qty: 77, fresh: true, calories: 200, price: 4.99},
  {name: "Barese Sausages", description: "Thin italian sausage with a mix of lamb and pork", qty: 20, fresh: true, calories: 401, price: 6.99},
  {name: "Sweet Italian", description: "pork sausage with white wine", qty: 20, fresh: true, calories: 300, price: 6.99},
  {name: "Bratwurst", description: "German sausages with veal and pork, with special German spices", qty: 190, fresh: true, calories: 12, price: 6.99},
  {name: "English Bangers", description: "Pork butt and spices", qty: 2, fresh: false, calories: 150, price: 4.99},
  {name: "Sicilian", description: "Whte wine , cheese, fennel and other delicios spices", qty: 195, fresh: true, calories: 500, price: 6.99},
  {name: "Bockwurst", description: "Pork and veal sauages", qty: 91, fresh: true, calories: 400, price: 6.99},
  {name: "Mortadella", description: "Italian baloney sausage", qty: 2, fresh: true, calories: 200, price: 3.99},
  {name: "Berliner Sausage", description: "Pork, veal and beef chuck", qty: 5, fresh: true, calories: 200, price: 6.99},
  {name: "Hard Salami ", description: "Cured beef, pork and pork back", qty: 1, fresh: false, calories: 300, price: 8.99},
  {name: "Breakfast Sausage", description: "Fresk Prok Butts", qty: 45, fresh: false, calories: 500, price: 8.99},
  {name: "Leberkase", description: "Contains beef,  pork trimmings, pork butt and pork liver", qty: 20, fresh: true, calories: 300, price: 3.99},
  {name: "Knockwurst", description: "Veal, prok trimmings, beef and pork fat", qty: 49, fresh: true, calories: 40, price: 8.99},
  {name: "Merquez Sausage", description: "Pork Butts, lamb and seasonings", qty: 198, fresh: false, calories: 400, price: 8.99},
  {name: "Chorizo", description: "Mexican pork sausage", qty: 43, fresh: true, calories: 300, price: 4.99},
  {name: "Kielbasa", description: "Polish Sausage", qty: 10, fresh: true, calories: 300, price: 5.99},
  {name: "Weisswurst", description: "German white sausage with veal and pork", qty: 8, fresh: true, calories: 450, price: 8.99},
  {name: "Beef Sausages", description: "Quality beef sausages", qty: 4, fresh: true, calories: 499, price: 8.99},
  {name: "Mild-Hot Italian", description: "Pork Sausage with Italian spices and crushed hot peppers", qty: 10, fresh: true, calories: 500, price: 5.99},
  {name: "Carmelo's Special", description: "Pork and Vea; with secret spices", qty: 10, fresh: true, calories: 10, price: 5.99},
  {name: "California Sausage", description: "Chicken and Herbs", qty: 9, fresh: false, calories: 200, price: 4.99}
])
User.create!([
  {name: "carmelo", password_digest: "$2a$10$sVEAWP7PMyQ.lHOMLXzgieY5uIKuOu6p0ZOKMhiw9fCPtLq25Xe3i"},
  {name: "tim", password_digest: "$2a$10$.lvFvnmKvNiJhIR6Ovbd/OgLSo.AkPFXww5aEyqdCatpGmhDHiNMG"},
  {name: "guest", password_digest: "$2a$10$u0E9cWHQTqItqPfiCxX/v.i18rRVO025XKmKz6z6X7j72kjPZoZqq"}
])
Order.create!([
  {name: "a customer", address: "a", email: "a", pay_type: "Credit Card", total_price: 32.99},
  {name: "b", address: "b", email: "b", pay_type: "Credit Card", total_price: 12.0},
  {name: "d", address: "d", email: "d", pay_type: "Check", total_price: 15.0},
  {name: "f", address: "f", email: "f", pay_type: "Credit Card", total_price: 10.0},
  {name: "e", address: "e", email: "e", pay_type: "Credit Card", total_price: 9.0},
  {name: "Carmelo Lattuca", address: "3301 Rill ct\r\nRocklin, CA\r\n95765", email: "lattuca@yahoo.com", pay_type: "Check", total_price: 9.0},
  {name: "joe", address: "addr", email: "11212", pay_type: "Credit Card", total_price: 9.0},
  {name: "carm", address: "sadsd", email: "asds", pay_type: "Credit Card", total_price: 9.0},
  {name: "d", address: "d", email: "d", pay_type: "Purchase order", total_price: 9.0},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 9.0},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Purchase order", total_price: 9.0},
  {name: "d", address: "d", email: "d", pay_type: "Check", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Credit Card", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Credit Card", total_price: 9.0},
  {name: "d", address: "d", email: "d", pay_type: "Credit Card", total_price: 9.0},
  {name: "z", address: "z", email: "z", pay_type: "Credit Card", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Check", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Check", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Check", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Check", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Check", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Check", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Check", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Check", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Check", total_price: 9.0},
  {name: "carm", address: "c", email: "c", pay_type: "Check", total_price: 9.0},
  {name: "carm", address: "c", email: "c", pay_type: "Check", total_price: 9.0},
  {name: "carm", address: "c", email: "c", pay_type: "Check", total_price: 9.0},
  {name: "carm", address: "c", email: "c", pay_type: "Check", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Check", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Check", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Check", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Check", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Check", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Purchase order", total_price: 9.0},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 9.0},
  {name: "e", address: "e", email: "e", pay_type: "Credit Card", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Credit Card", total_price: 9.0},
  {name: "dda", address: "asdsad", email: "dasdas", pay_type: "Credit Card", total_price: 9.0},
  {name: "d", address: "d", email: "d", pay_type: "Credit Card", total_price: 2.0},
  {name: "c", address: "c", email: "c", pay_type: "Credit Card", total_price: 9.0},
  {name: "r", address: "r", email: "r", pay_type: "Check", total_price: 9.0},
  {name: "d", address: "d", email: "d", pay_type: "Credit Card", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Purchase order", total_price: 9.0},
  {name: "a", address: "a", email: "as", pay_type: "Credit Card", total_price: 9.0},
  {name: "t", address: "t", email: "t", pay_type: "Credit Card", total_price: 9.0},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 9.0},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 9.0},
  {name: "4", address: "4", email: "4", pay_type: "Check", total_price: 9.0},
  {name: "r", address: "r", email: "r", pay_type: "Credit Card", total_price: 9.0},
  {name: "x", address: "x", email: "x", pay_type: "Credit Card", total_price: 11.11},
  {name: "d", address: "d", email: "d", pay_type: "Credit Card", total_price: 4.99},
  {name: "f", address: "d", email: "d", pay_type: "Credit Card", total_price: 4.99},
  {name: "dfd", address: "fdfd", email: "dfd", pay_type: "Credit Card", total_price: 11.98},
  {name: "a", address: "a", email: "asds", pay_type: "Credit Card", total_price: 11.98},
  {name: "fd", address: "dfd", email: "df", pay_type: "Credit Card", total_price: 6.99},
  {name: "tt", address: "ttt", email: "tt", pay_type: "Credit Card", total_price: 6.99},
  {name: "Carmelo Lattuca", address: "3301", email: "1221", pay_type: "Check", total_price: 17.98},
  {name: "joe", address: "boston", email: "joe", pay_type: "Credit Card", total_price: 6.99},
  {name: "d", address: "d", email: "d", pay_type: "Credit Card", total_price: 53.92000000000001},
  {name: "Carmelo Lattuca", address: "c", email: "c", pay_type: "Credit Card", total_price: 6.99},
  {name: "Carmelo Lattuca", address: "122", email: "wqw", pay_type: "Check", total_price: 6.99},
  {name: "2343", address: "243432", email: "23432", pay_type: "Credit Card", total_price: 13.98},
  {name: "2434", address: "434", email: "43242", pay_type: "Credit Card", total_price: 6.99},
  {name: "a", address: "a", email: "a", pay_type: "Credit Card", total_price: 6.99},
  {name: "x", address: "x", email: "x", pay_type: "Credit Card", total_price: 6.99},
  {name: "s", address: "s", email: "s", pay_type: "Check", total_price: 4.99},
  {name: "r", address: "r", email: "r", pay_type: "Purchase order", total_price: 6.99},
  {name: "4", address: "4", email: "4", pay_type: "Credit Card", total_price: 6.99},
  {name: "x", address: "x", email: "x", pay_type: "Purchase order", total_price: 22.97},
  {name: "t", address: "t", email: "t", pay_type: "Check", total_price: 6.99},
  {name: "r", address: "r", email: "r", pay_type: "Check", total_price: 4.99},
  {name: "r", address: "r", email: "r", pay_type: "Check", total_price: 8.0},
  {name: "r", address: "r", email: "r", pay_type: "Check", total_price: 8.99},
  {name: "r", address: "r", email: "r", pay_type: "Check", total_price: 6.99},
  {name: "t", address: "t", email: "t", pay_type: "Credit Card", total_price: 6.99},
  {name: "r", address: "r", email: "r", pay_type: "Check", total_price: 4.99},
  {name: "w", address: "w", email: "w", pay_type: "Credit Card", total_price: 6.99},
  {name: "r", address: "r", email: "r", pay_type: "Credit Card", total_price: 4.99},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 6.99},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 8.0},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 8.0},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 8.0},
  {name: "z", address: "z", email: "z", pay_type: "Credit Card", total_price: 11.98},
  {name: "z", address: "z", email: "z", pay_type: "Credit Card", total_price: 8.0},
  {name: "z", address: "z", email: "z", pay_type: "Credit Card", total_price: 8.0},
  {name: "z", address: "z", email: "z", pay_type: "Credit Card", total_price: 8.0},
  {name: "z", address: "z", email: "z", pay_type: "Credit Card", total_price: 8.0},
  {name: "aa", address: "aa", email: "aa", pay_type: "Credit Card", total_price: 22.97},
  {name: "aa", address: "aa", email: "aa", pay_type: "Credit Card", total_price: 8.0},
  {name: "Carmelo Lattucac", address: "c", email: "c", pay_type: "Credit Card", total_price: 6.99},
  {name: "a", address: "a", email: "a", pay_type: "Credit Card", total_price: 8.99},
  {name: "a", address: "aa", email: "a", pay_type: "Credit Card", total_price: 11.98},
  {name: "e", address: "e", email: "e", pay_type: "Credit Card", total_price: 6.99},
  {name: "a", address: "a", email: "a", pay_type: "Credit Card", total_price: 6.99},
  {name: "a", address: "a", email: "a", pay_type: "Credit Card", total_price: 8.0},
  {name: "f", address: "f", email: "f", pay_type: "Check", total_price: 6.99},
  {name: "t", address: "t", email: "t", pay_type: "Check", total_price: 6.99},
  {name: "sd", address: "ds", email: "sd", pay_type: "Credit Card", total_price: 4.99},
  {name: "r", address: "r", email: "r", pay_type: "Credit Card", total_price: 4.99},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 6.99},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 53.92000000000001},
  {name: "a", address: "a", email: "as", pay_type: "Check", total_price: 6.99},
  {name: "cc", address: "c", email: "c", pay_type: "Check", total_price: 8.99},
  {name: "v", address: "v", email: "v", pay_type: "Check", total_price: 6.99},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 4.99},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 32.95},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 6.99},
  {name: "aa", address: "a", email: "a", pay_type: "Credit Card", total_price: 6.99},
  {name: "aa", address: "a", email: "a", pay_type: "Credit Card", total_price: 8.0},
  {name: "aa", address: "a", email: "a", pay_type: "Credit Card", total_price: 8.0},
  {name: "aa", address: "a", email: "a", pay_type: "Credit Card", total_price: 8.0},
  {name: "aa", address: "a", email: "a", pay_type: "Credit Card", total_price: 8.0},
  {name: "aa", address: "a", email: "a", pay_type: "Credit Card", total_price: 8.0},
  {name: "aa", address: "a", email: "a", pay_type: "Credit Card", total_price: 8.0},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 8.99},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 8.0},
  {name: "x", address: "x", email: "x", pay_type: "Credit Card", total_price: 4.99},
  {name: "dfd", address: "d", email: "d", pay_type: "Credit Card", total_price: 6.99},
  {name: "s", address: "s", email: "s", pay_type: "Credit Card", total_price: 6.99},
  {name: "joe blow", address: "any place USA", email: "carmelo@sausages.com", pay_type: "Check", total_price: 29.96},
  {name: "Anna's Pizza", address: "2020 Rocklin Blvd\r\nRocklin, Ca\r\n95765", email: "annas@pizaa.com", pay_type: "Credit Card", total_price: 6.99},
  {name: "t", address: "t", email: "t", pay_type: "Credit Card", total_price: 6.99},
  {name: "df", address: "fds", email: "sdf", pay_type: "Credit Card", total_price: 11.98},
  {name: "ds", address: "ds", email: "ds", pay_type: "Check", total_price: 6.99},
  {name: "dda", address: "d", email: "dasdas", pay_type: "Credit Card", total_price: 5.99},
  {name: "x", address: "x", email: "x", pay_type: "Credit Card", total_price: 13.98},
  {name: "z", address: "z", email: "z", pay_type: "Check", total_price: 11.98},
  {name: "asd", address: "asd", email: "asd", pay_type: "Credit Card", total_price: 11.98},
  {name: "Lucy Lattuca", address: "Montreal", email: "lucy@gmail.com", pay_type: "Credit Card", total_price: 38.940000000000005},
  {name: "f", address: "f", email: "f", pay_type: "Credit Card", total_price: 17.98},
  {name: "as", address: "as", email: "as", pay_type: "Credit Card", total_price: 13.98},
  {name: "tt", address: "t", email: "tt", pay_type: "Credit Card", total_price: 13.98},
  {name: "ff", address: "f", email: "f", pay_type: "Credit Card", total_price: 6.99},
  {name: "ss", address: "sads", email: "ads", pay_type: "Check", total_price: 6.99},
  {name: "dfg", address: "dgfgd", email: "dfgdg", pay_type: "Check", total_price: 4.99},
  {name: "fdf", address: "sdgfd", email: "dfgf", pay_type: "Credit Card", total_price: 15.98},
  {name: "ds", address: "fds", email: "fsd", pay_type: "Check", total_price: 6.99},
  {name: "Anna's Pizza", address: "123", email: "24", pay_type: "Check", total_price: 4.99},
  {name: "r", address: "r", email: "r", pay_type: "Credit Card", total_price: 6.99},
  {name: "tt", address: "t", email: "t", pay_type: "Credit Card", total_price: 6.99},
  {name: "fds", address: "sdf", email: "sf", pay_type: "Check", total_price: 17.98},
  {name: "vc", address: "cvx", email: "xv", pay_type: "Credit Card", total_price: 8.99},
  {name: "dda", address: "asd", email: "asd", pay_type: "Credit Card", total_price: 8.99},
  {name: "asd", address: "dsa", email: "ads", pay_type: "Credit Card", total_price: 4.99},
  {name: "sddv", address: "zxcc", email: "zxcz", pay_type: "Credit Card", total_price: 6.99},
  {name: "sddv", address: "ddd", email: "dd", pay_type: "Credit Card", total_price: 6.99},
  {name: "ds", address: "d", email: "dasdas", pay_type: "Credit Card", total_price: 6.99},
  {name: "asjdbkjas", address: "sadsad", email: "asdsa", pay_type: "Credit Card", total_price: 15.98},
  {name: "sd", address: "s", email: "sdf", pay_type: "Credit Card", total_price: 6.99},
  {name: "sddvd", address: "d", email: "dasdas", pay_type: "Check", total_price: 6.99},
  {name: "cc", address: "c", email: "carmelo@sausages.com", pay_type: "Credit Card", total_price: 6.99},
  {name: "z", address: "z", email: "z", pay_type: "Credit Card", total_price: 6.99},
  {name: "e", address: "e", email: "e", pay_type: "Credit Card", total_price: 6.99},
  {name: "w", address: "w", email: "w", pay_type: "Credit Card", total_price: 6.99},
  {name: "1", address: "1", email: "1", pay_type: "Check", total_price: 13.98},
  {name: "1", address: "1", email: "1", pay_type: "Credit Card", total_price: 6.99},
  {name: "Carmelo Lattucac", address: "t", email: "tt", pay_type: "Credit Card", total_price: 6.99},
  {name: "w", address: "w", email: "wqw", pay_type: "Check", total_price: 6.99},
  {name: "e", address: "e", email: "e", pay_type: "Credit Card", total_price: 6.99},
  {name: "Carmelo Lattucac", address: "c", email: "carmelo@sausages.com", pay_type: "Purchase order", total_price: 6.99},
  {name: "x", address: "x", email: "x", pay_type: "Credit Card", total_price: 13.98},
  {name: "x", address: "x", email: "x", pay_type: "Check", total_price: 6.99},
  {name: "f", address: "f", email: "f", pay_type: "Check", total_price: 6.99},
  {name: "r", address: "r", email: "r", pay_type: "Check", total_price: 6.99},
  {name: "dfdd", address: "d", email: "d", pay_type: "Credit Card", total_price: 6.99},
  {name: "fd", address: "f", email: "f", pay_type: "Check", total_price: 6.99},
  {name: "t", address: "t", email: "tt", pay_type: "Credit Card", total_price: 6.99},
  {name: "dda", address: "d", email: "dfgdg", pay_type: "Check", total_price: 6.99},
  {name: "dd", address: "d", email: "dasdas", pay_type: "Check", total_price: 6.99},
  {name: "fdf", address: "f", email: "f", pay_type: "Check", total_price: 6.99},
  {name: "tt", address: "t", email: "t", pay_type: "Credit Card", total_price: 3.99},
  {name: "5", address: "5", email: "5", pay_type: "Check", total_price: 3.99},
  {name: "g", address: "g", email: "g", pay_type: "Check", total_price: 8.99},
  {name: "g", address: "g", email: "g", pay_type: "Check", total_price: 5.99},
  {name: "ttt", address: "t", email: "t", pay_type: "Credit Card", total_price: 6.99},
  {name: "r", address: "r", email: "r", pay_type: "Check", total_price: 8.99},
  {name: "m", address: "m", email: "m", pay_type: "Check", total_price: 13.98},
  {name: "y", address: "y", email: "y", pay_type: "Check", total_price: 6.99},
  {name: "g", address: "g", email: "g", pay_type: "Purchase order", total_price: 6.99},
  {name: "u", address: "u", email: "u", pay_type: "Credit Card", total_price: 8.99},
  {name: "fdff", address: "f", email: "f", pay_type: "Check", total_price: 4.99},
  {name: "joe blow", address: "l", email: "lucy@gmail.com", pay_type: "Check", total_price: 8.98},
  {name: "p", address: "p", email: "p", pay_type: "Credit Card", total_price: 5.99},
  {name: "k", address: "l", email: "lucy@gmail.com", pay_type: "Credit Card", total_price: 8.99},
  {name: "dsf", address: "fd", email: "g", pay_type: "Check", total_price: 9.98},
  {name: "x", address: "zx", email: "zx", pay_type: "Credit Card", total_price: 13.98},
  {name: "fds", address: "f", email: "fsd", pay_type: "Credit Card", total_price: 6.99},
  {name: "ccc", address: "c", email: "c", pay_type: "Check", total_price: 6.99},
  {name: "fdf", address: "f", email: "f", pay_type: "Credit Card", total_price: 6.99},
  {name: "ddad", address: "d", email: "dfgdg", pay_type: "Check", total_price: 6.99},
  {name: "u", address: "u", email: "u", pay_type: "Credit Card", total_price: 13.98},
  {name: "ddad", address: "d", email: "dfgdg", pay_type: "Check", total_price: 22.97},
  {name: "dddf", address: "fd", email: "fd", pay_type: "Credit Card", total_price: 22.97},
  {name: "dfg", address: "g", email: "g", pay_type: "Check", total_price: 13.98},
  {name: "ss", address: "s", email: "ss", pay_type: "Credit Card", total_price: 27.96},
  {name: "ss", address: "s", email: "ss", pay_type: "Credit Card", total_price: 8.0},
  {name: "e", address: "e", email: "e", pay_type: "Check", total_price: 6.99},
  {name: "asda", address: "asda", email: "ad", pay_type: "Check", total_price: 22.97},
  {name: "Carmelo Lattuca", address: "3301 Rill Ct", email: "lattuca@yahoo.com", pay_type: "Check", total_price: 170.74000000000004},
  {name: "sfds", address: "sdfds", email: "sdf", pay_type: "Credit Card", total_price: 36.95},
  {name: "dsfgdf", address: "dfgdf", email: "dfgfd", pay_type: "Check", total_price: 13.98},
  {name: "sds", address: "sdfds", email: "sdfds", pay_type: "Credit Card", total_price: 6.99},
  {name: "sdfsd", address: "sdf", email: "sdf", pay_type: "Check", total_price: 8.99},
  {name: "Carmelo Lattuca", address: "dsaf", email: "sfds", pay_type: "Credit Card", total_price: 15.98},
  {name: "dsf", address: "sdf", email: "sdf", pay_type: "Credit Card", total_price: 36.95},
  {name: "sddv", address: "s", email: "ss", pay_type: "Credit Card", total_price: 27.96},
  {name: "dsd", address: "sdf", email: "sdf", pay_type: "Credit Card", total_price: 23.96},
  {name: "dsf", address: "sdf", email: "sdf", pay_type: "Check", total_price: 4.99},
  {name: "asjdbkjas", address: "as", email: "as", pay_type: "Check", total_price: 13.98},
  {name: "fds", address: "sdf", email: "dsf", pay_type: "Check", total_price: 18.97},
  {name: "dsf", address: "sdf", email: "sdf", pay_type: "Check", total_price: 6.99},
  {name: "fs", address: "fds", email: "fsd", pay_type: "Credit Card", total_price: 6.99},
  {name: "sdf", address: "sdf", email: "dfgfd", pay_type: "Check", total_price: 13.98},
  {name: "dsfgdffsd", address: "sdf", email: "sdf", pay_type: "Credit Card", total_price: 6.99},
  {name: "sdf", address: "sdf", email: "sdf", pay_type: "Check", total_price: 6.99},
  {name: "dsfgdffsd", address: "sdf", email: "sdf", pay_type: "Credit Card", total_price: 6.99},
  {name: "dg", address: "df", email: "fgd", pay_type: "Check", total_price: 6.99},
  {name: "aa", address: "dsd", email: "sdfds", pay_type: "Check", total_price: 22.97},
  {name: "asd", address: "asds", email: "sfd", pay_type: "Credit Card", total_price: 15.98},
  {name: "asdas", address: "sdas", email: "asdas", pay_type: "Credit Card", total_price: 13.98},
  {name: "test", address: "werw", email: "ewrew", pay_type: "Credit Card", total_price: 13.98},
  {name: "vbn", address: "nbvn", email: "vbn", pay_type: "Check", total_price: 13.98},
  {name: "xcvxc", address: "xcvcxv", email: "xcvcx", pay_type: "Check", total_price: 15.98},
  {name: "Anna's Pizza", address: "234", email: "asds", pay_type: "Credit Card", total_price: 6.99},
  {name: "dsf", address: "dfs", email: "sdf", pay_type: "Check", total_price: 8.99},
  {name: "Dominic's Italian Deli", address: "456 Auburn-Folsom Rd\r\nGranite Bay, CA", email: "luigi@domincsdeli.com", pay_type: "Credit Card", total_price: 15.98},
  {name: "Dominic's Italian Deli", address: "qwe", email: "zxzX", pay_type: "Credit Card", total_price: 8.99},
  {name: "z", address: "z", email: "zx", pay_type: "Credit Card", total_price: 9.98}
])
Cart.create!([
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {}
])
LineItem.create!([
  {sausage_id: 2, cart_id: 1, quantity: 1, order_id: 1},
  {sausage_id: 3, cart_id: 2, quantity: 1, order_id: 1},
  {sausage_id: 3, cart_id: 2, quantity: 1, order_id: 1},
  {sausage_id: 1, cart_id: 2, quantity: 1, order_id: 1},
  {sausage_id: 4, cart_id: 2, quantity: 1, order_id: 1},
  {sausage_id: 4, cart_id: 2, quantity: 1, order_id: 1},
  {sausage_id: 3, cart_id: 2, quantity: 1, order_id: 1},
  {sausage_id: 2, cart_id: 2, quantity: 1, order_id: 1},
  {sausage_id: 4, cart_id: 2, quantity: 1, order_id: 1},
  {sausage_id: 1, cart_id: 2, quantity: 1, order_id: 1},
  {sausage_id: 4, cart_id: 2, quantity: 1, order_id: 1},
  {sausage_id: 1, cart_id: 2, quantity: 1, order_id: 1},
  {sausage_id: 1, cart_id: 2, quantity: 1, order_id: 1},
  {sausage_id: 4, cart_id: 2, quantity: 1, order_id: 1},
  {sausage_id: 3, cart_id: 2, quantity: 1, order_id: 1},
  {sausage_id: 3, cart_id: 3, quantity: 2, order_id: 1},
  {sausage_id: 3, cart_id: 3, quantity: 1, order_id: 1},
  {sausage_id: 4, cart_id: 3, quantity: 2, order_id: 1},
  {sausage_id: 3, cart_id: 3, quantity: 1, order_id: 1},
  {sausage_id: 2, cart_id: 3, quantity: 1, order_id: 1},
  {sausage_id: 1, cart_id: 3, quantity: 2, order_id: 1},
  {sausage_id: 1, cart_id: 3, quantity: 1, order_id: 1},
  {sausage_id: 7, cart_id: 7, quantity: 1, order_id: 1},
  {sausage_id: 5, cart_id: 7, quantity: 2, order_id: 1},
  {sausage_id: 2, cart_id: 7, quantity: 2, order_id: 1},
  {sausage_id: 9, cart_id: 7, quantity: 1, order_id: 1},
  {sausage_id: 3, cart_id: 7, quantity: 1, order_id: 1},
  {sausage_id: 8, cart_id: 7, quantity: 1, order_id: 1},
  {sausage_id: 10, cart_id: 7, quantity: 2, order_id: 2},
  {sausage_id: 12, cart_id: 7, quantity: 1, order_id: 2},
  {sausage_id: 14, cart_id: 7, quantity: 1, order_id: 2},
  {sausage_id: 5, cart_id: 8, quantity: 2, order_id: 2},
  {sausage_id: 13, cart_id: 8, quantity: 2, order_id: 2},
  {sausage_id: 12, cart_id: 8, quantity: 1, order_id: 2},
  {sausage_id: 5, cart_id: nil, quantity: 1, order_id: 1},
  {sausage_id: 6, cart_id: nil, quantity: 1, order_id: 1},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 1},
  {sausage_id: 10, cart_id: nil, quantity: 1, order_id: 1},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 2},
  {sausage_id: 12, cart_id: nil, quantity: 1, order_id: 3},
  {sausage_id: 1, cart_id: nil, quantity: 1, order_id: 3},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 4},
  {sausage_id: 12, cart_id: nil, quantity: 1, order_id: 5},
  {sausage_id: 12, cart_id: nil, quantity: 1, order_id: 6},
  {sausage_id: 6, cart_id: nil, quantity: 1, order_id: 7},
  {sausage_id: 1, cart_id: nil, quantity: 1, order_id: 7},
  {sausage_id: 14, cart_id: nil, quantity: 1, order_id: 8},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 8},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 9},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 9},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 10},
  {sausage_id: 3, cart_id: nil, quantity: 1, order_id: 12},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 12},
  {sausage_id: 10, cart_id: nil, quantity: 1, order_id: 12},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 13},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 14},
  {sausage_id: 6, cart_id: nil, quantity: 1, order_id: 15},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 16},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 17},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 18},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 27},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 31},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 36},
  {sausage_id: 9, cart_id: nil, quantity: 2, order_id: 37},
  {sausage_id: 5, cart_id: nil, quantity: 1, order_id: 37},
  {sausage_id: 14, cart_id: nil, quantity: 1, order_id: 37},
  {sausage_id: 6, cart_id: nil, quantity: 1, order_id: 37},
  {sausage_id: 1, cart_id: nil, quantity: 1, order_id: 37},
  {sausage_id: 13, cart_id: nil, quantity: 1, order_id: 37},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 38},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 39},
  {sausage_id: 16, cart_id: nil, quantity: 1, order_id: 40},
  {sausage_id: 13, cart_id: nil, quantity: 1, order_id: 40},
  {sausage_id: 14, cart_id: nil, quantity: 1, order_id: 40},
  {sausage_id: 10, cart_id: nil, quantity: 1, order_id: 40},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 40},
  {sausage_id: 9, cart_id: nil, quantity: 2, order_id: 40},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 41},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 42},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 42},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 43},
  {sausage_id: 14, cart_id: nil, quantity: 1, order_id: 44},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 45},
  {sausage_id: 10, cart_id: nil, quantity: 1, order_id: 45},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 45},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 46},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 47},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 48},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 48},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 49},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 49},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 49},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 50},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 51},
  {sausage_id: 2, cart_id: nil, quantity: 2, order_id: 52},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 52},
  {sausage_id: 5, cart_id: nil, quantity: 1, order_id: 53},
  {sausage_id: 5, cart_id: nil, quantity: 1, order_id: 54},
  {sausage_id: 1, cart_id: nil, quantity: 1, order_id: 55},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 55},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 56},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 56},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 57},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 58},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 59},
  {sausage_id: 14, cart_id: nil, quantity: 1, order_id: 59},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 60},
  {sausage_id: 9, cart_id: nil, quantity: 3, order_id: 61},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 61},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 61},
  {sausage_id: 1, cart_id: nil, quantity: 1, order_id: 61},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 61},
  {sausage_id: 5, cart_id: nil, quantity: 1, order_id: 61},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 62},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 63},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 64},
  {sausage_id: 3, cart_id: nil, quantity: 1, order_id: 64},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 65},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 66},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 67},
  {sausage_id: 1, cart_id: nil, quantity: 1, order_id: 68},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 69},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 70},
  {sausage_id: 7, cart_id: nil, quantity: 2, order_id: 71},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 71},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 72},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 73},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 75},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 76},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 77},
  {sausage_id: 1, cart_id: nil, quantity: 1, order_id: 78},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 79},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 80},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 81},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 85},
  {sausage_id: 5, cart_id: nil, quantity: 1, order_id: 85},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 90},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 90},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 90},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 92},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 93},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 94},
  {sausage_id: 5, cart_id: nil, quantity: 1, order_id: 94},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 95},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 96},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 98},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 99},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 100},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 101},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 102},
  {sausage_id: 5, cart_id: nil, quantity: 1, order_id: 103},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 103},
  {sausage_id: 4, cart_id: nil, quantity: 2, order_id: 103},
  {sausage_id: 10, cart_id: nil, quantity: 1, order_id: 103},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 103},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 103},
  {sausage_id: 1, cart_id: nil, quantity: 1, order_id: 103},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 104},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 105},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 106},
  {sausage_id: 5, cart_id: nil, quantity: 1, order_id: 107},
  {sausage_id: 7, cart_id: nil, quantity: 2, order_id: 108},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 108},
  {sausage_id: 5, cart_id: nil, quantity: 2, order_id: 108},
  {sausage_id: 3, cart_id: nil, quantity: 1, order_id: 109},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 110},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 117},
  {sausage_id: 5, cart_id: nil, quantity: 1, order_id: 119},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 120},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 121},
  {sausage_id: 11, cart_id: nil, quantity: 2, order_id: 122},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 122},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 122},
  {sausage_id: 6, cart_id: nil, quantity: 1, order_id: 123},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 124},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 125},
  {sausage_id: 5, cart_id: nil, quantity: 1, order_id: 125},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 126},
  {sausage_id: 16, cart_id: nil, quantity: 1, order_id: 127},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 128},
  {sausage_id: 5, cart_id: nil, quantity: 1, order_id: 128},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 129},
  {sausage_id: 1, cart_id: nil, quantity: 1, order_id: 129},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 130},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 130},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 131},
  {sausage_id: 2, cart_id: nil, quantity: 3, order_id: 131},
  {sausage_id: 12, cart_id: nil, quantity: 1, order_id: 131},
  {sausage_id: 14, cart_id: nil, quantity: 1, order_id: 131},
  {sausage_id: 10, cart_id: nil, quantity: 2, order_id: 132},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 133},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 133},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 134},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 134},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 135},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 136},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 137},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 138},
  {sausage_id: 10, cart_id: nil, quantity: 1, order_id: 138},
  {sausage_id: 5, cart_id: nil, quantity: 1, order_id: 138},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 139},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 140},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 141},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 142},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 142},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 142},
  {sausage_id: 11, cart_id: nil, quantity: 2, order_id: 143},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 144},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 145},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 145},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 145},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 146},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 147},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 148},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 149},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 149},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 149},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 150},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 150},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 151},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 152},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 153},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 154},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 155},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 156},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 157},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 157},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 158},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 159},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 160},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 161},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 162},
  {sausage_id: 4, cart_id: nil, quantity: 2, order_id: 163},
  {sausage_id: 3, cart_id: nil, quantity: 1, order_id: 164},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 165},
  {sausage_id: 3, cart_id: nil, quantity: 1, order_id: 166},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 167},
  {sausage_id: 6, cart_id: nil, quantity: 1, order_id: 168},
  {sausage_id: 6, cart_id: nil, quantity: 1, order_id: 169},
  {sausage_id: 6, cart_id: nil, quantity: 1, order_id: 170},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 171},
  {sausage_id: 6, cart_id: nil, quantity: 1, order_id: 172},
  {sausage_id: 8, cart_id: nil, quantity: 1, order_id: 173},
  {sausage_id: 16, cart_id: nil, quantity: 1, order_id: 176},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 177},
  {sausage_id: 7, cart_id: nil, quantity: 2, order_id: 179},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 180},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 181},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 183},
  {sausage_id: 1, cart_id: nil, quantity: 1, order_id: 184},
  {sausage_id: 12, cart_id: nil, quantity: 1, order_id: 184},
  {sausage_id: 16, cart_id: nil, quantity: 1, order_id: 185},
  {sausage_id: 10, cart_id: nil, quantity: 1, order_id: 186},
  {sausage_id: 1, cart_id: nil, quantity: 1, order_id: 187},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 187},
  {sausage_id: 3, cart_id: nil, quantity: 1, order_id: 188},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 188},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 189},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 190},
  {sausage_id: 6, cart_id: nil, quantity: 1, order_id: 191},
  {sausage_id: 6, cart_id: nil, quantity: 1, order_id: 192},
  {sausage_id: 14, cart_id: nil, quantity: 1, order_id: 193},
  {sausage_id: 1, cart_id: nil, quantity: 1, order_id: 193},
  {sausage_id: 14, cart_id: nil, quantity: 1, order_id: 194},
  {sausage_id: 6, cart_id: nil, quantity: 1, order_id: 194},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 194},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 195},
  {sausage_id: 6, cart_id: nil, quantity: 1, order_id: 195},
  {sausage_id: 13, cart_id: nil, quantity: 1, order_id: 195},
  {sausage_id: 3, cart_id: nil, quantity: 2, order_id: 196},
  {sausage_id: 2, cart_id: nil, quantity: 2, order_id: 197},
  {sausage_id: 9, cart_id: nil, quantity: 2, order_id: 197},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 199},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 200},
  {sausage_id: 10, cart_id: nil, quantity: 1, order_id: 200},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 200},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 1},
  {sausage_id: 2, cart_id: nil, quantity: 15, order_id: 201},
  {sausage_id: 9, cart_id: nil, quantity: 3, order_id: 201},
  {sausage_id: 15, cart_id: nil, quantity: 2, order_id: 201},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 201},
  {sausage_id: 7, cart_id: nil, quantity: 2, order_id: 201},
  {sausage_id: 8, cart_id: nil, quantity: 1, order_id: 201},
  {sausage_id: 1, cart_id: nil, quantity: 1, order_id: 201},
  {sausage_id: 5, cart_id: nil, quantity: 1, order_id: 201},
  {sausage_id: 2, cart_id: nil, quantity: 2, order_id: 202},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 202},
  {sausage_id: 10, cart_id: nil, quantity: 1, order_id: 202},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 202},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 203},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 203},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 204},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 205},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 206},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 206},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 207},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 207},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 207},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 207},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 207},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 208},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 208},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 208},
  {sausage_id: 10, cart_id: nil, quantity: 1, order_id: 208},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 209},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 209},
  {sausage_id: 5, cart_id: nil, quantity: 2, order_id: 209},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 210},
  {sausage_id: 2, cart_id: nil, quantity: 2, order_id: 211},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 212},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 212},
  {sausage_id: 15, cart_id: nil, quantity: 1, order_id: 212},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 213},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 214},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 215},
  {sausage_id: 7, cart_id: nil, quantity: 1, order_id: 215},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 216},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 217},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 218},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 128},
  {sausage_id: 9, cart_id: nil, quantity: 1, order_id: 219},
  {sausage_id: 2, cart_id: nil, quantity: 2, order_id: 221},
  {sausage_id: 18, cart_id: nil, quantity: 1, order_id: 221},
  {sausage_id: 18, cart_id: nil, quantity: 1, order_id: 222},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 222},
  {sausage_id: 2, cart_id: nil, quantity: 2, order_id: 224},
  {sausage_id: 2, cart_id: nil, quantity: 2, order_id: 225},
  {sausage_id: 2, cart_id: nil, quantity: 2, order_id: 226},
  {sausage_id: 18, cart_id: nil, quantity: 1, order_id: 227},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 227},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 228},
  {sausage_id: 18, cart_id: nil, quantity: 1, order_id: 229},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 229},
  {sausage_id: 18, cart_id: nil, quantity: 1, order_id: 229},
  {sausage_id: 18, cart_id: nil, quantity: 1, order_id: 230},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 230},
  {sausage_id: 11, cart_id: nil, quantity: 1, order_id: 230},
  {sausage_id: 1, cart_id: nil, quantity: 1, order_id: 230},
  {sausage_id: 5, cart_id: nil, quantity: 1, order_id: 230},
  {sausage_id: 2, cart_id: nil, quantity: 1, order_id: 230},
  {sausage_id: 4, cart_id: nil, quantity: 1, order_id: 230}
])
